version: "3.4"

services:
    website:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
                - "8080:8080"

    sql1:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "AlumniDb2023"
            ACCEPT_EULA: "Y"


